In [54]:
import pandas as pd

In [55]:
df_viagens = pd.read_csv('../data/raw/2023_Viagem.csv', encoding='Windows-1252', sep=';',decimal=',', thousands='.')

In [56]:
df_viagens.shape

(826989, 22)

In [57]:
df_viagens.dtypes

Identificador do processo de viagem      int64
Número da Proposta (PCDP)                  str
Situação                                   str
Viagem Urgente                             str
Justificativa Urgência Viagem              str
Código do órgão superior                 int64
Nome do órgão superior                     str
Código órgão solicitante                 int64
Nome órgão solicitante                     str
CPF viajante                               str
Nome                                       str
Cargo                                      str
Função                                     str
Descrição Função                           str
Período - Data de início                   str
Período - Data de fim                      str
Destinos                                   str
Motivo                                     str
Valor diárias                          float64
Valor passagens                        float64
Valor devolução                        float64
Valor outros gastos                    float64
dtype: object

In [58]:
df_viagens.head()

,Identificador do processo de viagem,Número da Proposta (PCDP),Situação,Viagem Urgente,Justificativa Urgência Viagem,Código do órgão superior,Nome do órgão superior,Código órgão solicitante,Nome órgão solicitante,CPF viajante,Nome,Cargo,Função,Descrição Função,Período - Data de início,Período - Data de fim,Destinos,Motivo,Valor diárias,Valor passagens,Valor devolução,Valor outros gastos
0,17821923,000001/23-1C,Realizada,NÃO,Sem informação,26000,Ministério da Educação,26352,Fundação Universidade Federal do ABC,***.875.238-**,PRISCILA LEAL DA SILVA,PROFESSOR DO MAGISTERIO SUPERIOR,-1,Sem informação,01/01/2023,02/12/2023,Loughborough/Reino Unido,Intercâmbio acadêmico PCDP anterior 07/21-3C,0.00,0.00,0.0,0.00
1,18236583,000018/23,Realizada,NÃO,Sem informação,26000,Ministério da Educação,26236,Universidade Federal Fluminense,NaN,CAMILLA DUARTE DA SILVA,BIBLIOTECARIO-DOCUMENTALISTA,-1,Sem informação,16/01/2023,28/02/2024,Rio de Janeiro/RJ,Afastamento para pós-graduação stricto sensu n...,0.00,0.00,0.0,0.00
2,18288418,000007/23-1C,Realizada,SIM,Por necessidade do serviço.,52000,Ministério da Defesa,52121,Comando do Exército,***.621.358-**,ANDRE LUIS COSTA PITANGUEIRA,NaN,OfSuperior,OfSuperior,10/01/2023,29/01/2023,Nova York/Estados Unidos da América,Participar da revisão do COE Manual (Contingen...,39565.70,7434.13,0.0,1095.35
3,18296348,000070/23,Realizada,SIM,A efetivação do empenho no Siafi e a respectiv...,26000,Ministério da Educação,26406,Instituto Federal do Espírito Santo,***.407.547-**,LIDIANY MIRANDA FERRAZ NUNES,AUXILIAR DE BIBLIIOTECA,-1,Sem informação,05/02/2023,10/02/2023,Vitória/ES,Participação das aulas de Mestrado Interinstit...,1013.96,0.00,0.0,0.00
4,18302983,000001/23,Realizada,NÃO,Sem informação,52000,Ministério da Defesa,52111,Comando da Aeronáutica,***.855.388-**,GREGOR GASPAR,NaN,OfIntermed,OfIntermed,01/01/2023,07/07/2023,Gotemburgo/Suécia,PARTICIPAR DO CURSO DE PILOTO DE GRIPEN C/D.,0.00,14903.10,0.0,0.00

In [59]:
df_viagens.columns

Index(['Identificador do processo de viagem', 'Número da Proposta (PCDP)',
       'Situação', 'Viagem Urgente', 'Justificativa Urgência Viagem',
       'Código do órgão superior', 'Nome do órgão superior',
       'Código órgão solicitante', 'Nome órgão solicitante', 'CPF viajante',
       'Nome', 'Cargo', 'Função', 'Descrição Função',
       'Período - Data de início', 'Período - Data de fim', 'Destinos',
       'Motivo', 'Valor diárias', 'Valor passagens', 'Valor devolução',
       'Valor outros gastos'],
      dtype='str')

In [60]:
df_viagens[[
    'Valor diárias', 
    'Valor passagens', 
    'Valor devolução',
    'Valor outros gastos'
]]

        Valor diárias  Valor passagens  Valor devolução  Valor outros gastos
0                0.00             0.00              0.0                 0.00
1                0.00             0.00              0.0                 0.00
2            39565.70          7434.13              0.0              1095.35
3             1013.96             0.00              0.0                 0.00
4                0.00         14903.10              0.0                 0.00
...               ...              ...              ...                  ...
826984         606.89          3331.29              0.0                 0.00
826985        1089.00          1837.18              0.0                 0.00
826986         734.13          4555.95              0.0                 0.00
826987         319.28          3745.53              0.0               400.00
826988           0.00          2961.55              0.0                 0.00

[826989 rows x 4 columns]

In [61]:
df_viagens['Despesas'] = df_viagens['Valor diárias'] + df_viagens['Valor passagens'] - df_viagens['Valor devolução'] + df_viagens['Valor outros gastos']

In [62]:
df_viagens.columns

Index(['Identificador do processo de viagem', 'Número da Proposta (PCDP)',
       'Situação', 'Viagem Urgente', 'Justificativa Urgência Viagem',
       'Código do órgão superior', 'Nome do órgão superior',
       'Código órgão solicitante', 'Nome órgão solicitante', 'CPF viajante',
       'Nome', 'Cargo', 'Função', 'Descrição Função',
       'Período - Data de início', 'Período - Data de fim', 'Destinos',
       'Motivo', 'Valor diárias', 'Valor passagens', 'Valor devolução',
       'Valor outros gastos', 'Despesas'],
      dtype='str')

In [63]:
df_viagens['Despesas'].describe()

count    826989.000000
mean       2760.577198
std        5876.719878
min        -589.910000
25%         409.710000
50%        1249.950000
75%        3343.120000
max      195192.150000
Name: Despesas, dtype: float64

In [64]:
df_viagens[df_viagens['Despesas'] == 0]['Situação'].value_counts()

Situação
Realizada        35958
Não realizada     8208
Name: count, dtype: int64

In [65]:
df_viagens['Situação'].value_counts()

Situação
Realizada        810309
Não realizada     16680
Name: count, dtype: int64

In [66]:
df_viagens[df_viagens['Despesas'] < 0]['Situação'].value_counts()

Situação
Realizada    8
Name: count, dtype: int64

In [67]:
df_viagens[df_viagens['Despesas'] < 0][['Valor diárias', 'Valor passagens', 'Valor devolução', 'Valor outros gastos', 'Despesas']]

,Valor diárias,Valor passagens,Valor devolução,Valor outros gastos,Despesas
10101,3593.17,0.00,3703.50,0.0,-110.33
49114,451.35,0.00,601.80,0.0,-150.45
203724,0.00,0.00,41.66,0.0,-41.66
213611,0.00,848.29,1438.20,0.0,-589.91
231550,0.00,0.00,50.75,0.0,-50.75
352686,391.53,0.00,541.98,0.0,-150.45
401430,0.00,0.00,4.68,0.0,-4.68
782450,511.61,0.00,511.90,0.0,-0.29

In [68]:
df_viagens[['Cargo', 'Destinos', 'Despesas']].nlargest(10,'Despesas')

,Cargo,Destinos,Despesas
466711,MINISTRO DE PRIMEIRA CLASSE,"Jacarta/Indonésia, Phnom Penh/Camboja, Nova Yo...",195192.15
129058,NaN,"Xangai/China, São Paulo/SP",192676.02
129008,NaN,"Xangai/China, São Paulo/SP",192048.56
206998,Informações protegidas por sigilo,Informações protegidas por sigilo,184787.42
1869,NaN,Lisboa/Portugal,172866.17
168228,MINISTRO DE PRIMEIRA CLASSE,"Xangai/China, Pequim/China",164821.02
504113,PESQUISADOR EM SAUDE PUBLICA,"Havana/Cuba, Nova York/Estados Unidos da América",164108.66
7339,NaN,"Brasília/DF, Brasília/DF, Rio de Janeiro/RJ, B...",163129.52
261765,MINISTRO DE PRIMEIRA CLASSE,Brasília/DF,157584.06
218975,ANALISTA DE PLANEJAMENTO E ORCAMENTO,Manama/Bareine,157255.53

In [69]:
df_viagens['Destinos'].head(20)

0                Loughborough/Reino Unido
1                       Rio de Janeiro/RJ
2     Nova York/Estados Unidos da América
3                              Vitória/ES
4                       Gotemburgo/Suécia
5       Informações protegidas por sigilo
6                       Gotemburgo/Suécia
7                       Gotemburgo/Suécia
8                       Gotemburgo/Suécia
9                                Natal/RN
10                               Natal/RN
11                               Natal/RN
12                              Gurupi/TO
13      Informações protegidas por sigilo
14    Nova York/Estados Unidos da América
15                      Rio de Janeiro/RJ
16                      Rio de Janeiro/RJ
17    Nova York/Estados Unidos da América
18                           Fortaleza/CE
19                            Brasília/DF
Name: Destinos, dtype: str